name: Build and Deploy Pages

on:
  push:
    branches:
    - master

jobs:

  build-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [16]

    steps:

    - uses: actions/checkout@v2

    - name: Build 
      working-directory: ./explorer
      env:
        CI: ""
      run: |
        npm install
        npm run-script build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./explorer/build